### ISSUE TITLE
Socket doesn't disconnect correctly

### ISSUE THREAD

**Issue by a-lchen** [eycai/tractor#8]
Instead of sending the "/leave_room" POST, I think we should auto remove a user from a room when they leave (e.g., they press the x button their browser or back). The Socket Event for that is on('disconnect') i think the server already has a handler for it, but right now it just logs and doesn't do anything to the rooms. Is it possible, on the server side, once a user disconnects

1) remove the user from all rooms, and all mappings
2) broadcast that the user left to all other users in that room 

thoughts?

**Comment by a-lchen** [comment]
Also, another thing to think about... what if the host disconnects from a room lol

**Comment by eycai** [comment]
This will... require some refactoring, but should be possible. 

If the host leaves, we can probably reassign host to the second user who joined?

**Comment by a-lchen** [comment]
Yeah that's fine with me: sorry I should've thought of this earlier... when I say "broadcast" just do a normal room update message

**Comment by a-lchen** [comment]
my FE will be able to handle it gracefully

**Comment by eycai** [comment]
ok sounds good, will work on this tonight

**Comment by eycai** [comment]
hmm I added this but I don't think my server is receiving the disconnect event when I close the tab, until like a minute later (and it's accompanied by a timeout error)? is this expected?
