### ISSUE TITLE
User can join a room multiple times

### ISSUE THREAD

**Issue by a-lchen** [eycai/tractor#9]
Opening up multiple tabs allows the same user to join a room multiple times lol, we should probably not allow the same user to connect to the server multiple times... Thoughts on how to deal with this?

One way is when the user sends over that connection request, we can slap it away if they are already connected and send back a response that's like "yo you already connected can u maybe chill"

**Comment by eycai** [comment]
Hmm we can also make joining a room idempotent (and just do nothing/return 200)? Depends what the frontend use case is for /join_room.
If it's just that you see the game room, I don't think there's a problem with showing the room in multiple windows; alternatively I can add a block and return an error or something.

**Comment by a-lchen** [comment]
I think the issue is that every time you open a new window and connect to it, you get a new socket connection, so the room gets a new user

**Comment by a-lchen** [comment]
So you get fun stuff like this:

![image](https://user-images.githubusercontent.com/23608409/77815812-10996c80-707b-11ea-8b5d-802df7f3b587.png)

**Comment by eycai** [comment]
Oh in that case maybe we just need to allow users to have multiple socket connections? (I can still add the block and not add the user to the room a second time)

**Comment by a-lchen** [comment]
Having multiple sockets per user means that we have to send to all the sockets, I think a better solution here is if you connect a new socket you boot off the old one?

**Comment by a-lchen** [comment]
then we can send a socket message down the old socket and be like, hey btw you just got booted off. I'll display a message that's like "hey sorry a new tab was opened so this tab is no longer active"

**Comment by eycai** [comment]
Hmm ok I think this works, so once the frontend sends the /connect POST to connect the new socket, I boot off old sockets with a message like "disconnect" and reroute all the mappings

**Comment by a-lchen** [comment]
Let's call the message "stale"
